/**
 * Meow capabilities (ADR-0025). Mirrors the backend union in
 * `modules/meow/interface/ICapability.ts`.
 *
 * Structured execution only: the caller names the capability and supplies typed
 * params. There is no free-text parsing and no AI call on this path, so a
 * capability always executes with zero tokens.
 */
export const MEOW_CAPABILITIES = [
  'VIEW_MY_DAY',
  'CREATE_TASK',
  'COMPLETE_TASK',
  'REASSIGN_TASK',
  'CREATE_EVENT',
  'ADD_SHOPPING_ITEM',
  'VIEW_INVENTORY',
  'VIEW_EXPENSE_BALANCE',
  'VIEW_SAVINGS',
  'CONTRIBUTE_SAVINGS',
  'VIEW_PET_CARE',
  'START_PREMIUM_MODULE',
] as const;

export type MeowCapability = (typeof MEOW_CAPABILITIES)[number];

/** Params are per-capability and validated server-side. */
export type MeowCapabilityParams = Record<string, unknown>;

/** Mirrors the backend `IMeowCapabilityResponse`. */
export interface MeowCapabilityResult {
  capability: MeowCapability;
  /** Deterministic, template-based confirmation — never generated by the AI. */
  message: string;
  /** Per-capability payload; the shape varies, so it stays opaque here. */
  data: unknown;
  /** Optional phrase-bank line, only some capabilities attach one. */
  phrase: string | null;
}
