export type RootStackParamList = {
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  Dashboard: undefined;
  CreateHousehold: undefined;
  TasksList: undefined;
  TaskDetail: { taskId: string };
  TaskForm: undefined;
  ShoppingLists: undefined;
  ShoppingItemForm: { listId: string };
  InventoryList: undefined;
  InventoryItemDetail: { itemId: string };
  Expenses: undefined;
  ExpenseDetail: { expenseId: string };
  ExpenseForm: undefined;
  Savings: undefined;
  SavingsGoalDetail: { goalId: string };
  SavingsGoalForm: undefined;
  Calendar: undefined;
  CalendarEventDetail: { eventId: string };
  CalendarEventForm: { eventId?: string };
  NotificationsList: undefined;
  Pets: undefined;
  PetDetail: { petId: string };
  PetForm: { petId?: string };
};
